### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by bach5000**

### CODE REVIEW

**Comment by korli** [comment]
Looks OK. The game cannot be played with the mouse, right?

**Comment by janus2** [comment]
I think the screenshots for the applications should use the original theme of Haiku.

**Comment by humdingerb** [comment]
Right! Get ThemeManager to switch between default and your perverse green tabs. :)

**Comment by owenca** [comment]
> I don't know if you can squash commits with Github website...
It would be easier to squash locally and then push.

**Comment by bach5000** [comment]
Ok. Updated the screenshot :)
@owenca As for squashing commits, I read the following docs: https://github.com/wprig/wprig/wiki/How-to-squash-commits, but I still have no idea what I'm doing... since there are still 4 different commits shown on this PR, I guess it was a failure 😅

**Comment by owenca** [comment]
> Ok. Updated the screenshot :)
> @owenca As for squashing commits, I read the following docs: https://github.com/wprig/wprig/wiki/How-to-squash-commits, but I still have no idea what I'm doing... since there are still 4 different commits shown on this PR, I guess it was a failure 😅

Try this:
`git rebase -i HEAD~n`, where `n` is the number of most recent commits you want to squash.
Then `git log` to make sure the outcome is what you expected.
Finally, `git push -f`.

**Pull request merged**
